### PR TITLE
Updated simple_gmap module and added a patch to moderation_dashboard module.

### PR DESCRIPTION
**Pull request by Vinay15**

### CODE REVIEW

**Review by vaibhavjain-in — COMMENTED** [review]
@Vinay15 How does the version change affect us ?

**Comment by Vinay15** [comment]
@vaibhavjain-in 
EZContent profile installation breaks with Acquia BLT setup, as the blt project has simple_gmap (8.x-2.0) module.
The composer create-project srijanone/ezcontent-project also breaks as its not able to apply patch to moderation_dashboard.
So, in order to check if what changes are there in simple_gmap (2.0) and how those affect us, the installation is not going through to verify the same.

**Review by vaibhavjain-in — APPROVED** [review]
Let's merge and test this.

**Comment by Vinay15** [comment]
@vaibhavjain-in Please approve.

**Pull request merged**
